"""Create output folders and consolidate simulation result files."""

from pathlib import Path
import shutil
import hashlib
import json
import os
import time
from datetime import date, datetime, time as datetime_time

import numpy as np
import pandas as pd
from src.analysis.scenario import get_output_level
from src.analysis.scenario import should_save_detailed_output


def get_output_paths(module_file, user):
    """Return scenario output, temporary, and forecast directories."""

    module_dir = Path(module_file).resolve().parents[2]
    scenario_dir = module_dir / user["scenario_folder"]
    scenario_dir /= user["scenario_subfolder"]
    output_dir = scenario_dir / "Output"
    temp_dir = output_dir / "MC_temp"
    forecast_dir = scenario_dir / "Perturbed_Forecasts"
    output_dir.mkdir(parents=True, exist_ok=True)
    return output_dir, temp_dir, forecast_dir


def _stable_cell_value(value):
    """Return a deterministic JSON-compatible Excel cell value."""

    if value is None:
        return {"type": "none", "value": None}
    if isinstance(value, bool):
        return {"type": "bool", "value": value}
    if isinstance(value, int):
        return {"type": "int", "value": value}
    if isinstance(value, float):
        if pd.isna(value):
            text = "nan"
        elif value == float("inf"):
            text = "inf"
        elif value == float("-inf"):
            text = "-inf"
        else:
            text = value.hex()
        return {"type": "float", "value": text}
    if isinstance(value, (datetime, date, datetime_time)):
        return {"type": "datetime", "value": value.isoformat()}
    return {"type": type(value).__name__, "value": str(value)}


def _hash_excel_file(file_path):
    """Hash workbook cell contents without volatile Excel metadata."""

    digest = hashlib.sha256()
    from openpyxl import load_workbook

    workbook = load_workbook(
        file_path,
        read_only=True,
        data_only=False,)
    try:
        for worksheet in workbook.worksheets:
            header = {
                "sheet": worksheet.title,
                "rows": worksheet.max_row,
                "columns": worksheet.max_column,}
            digest.update(json.dumps(
                header,
                sort_keys=True,
                separators=(",", ":"),
                ensure_ascii=False,).encode("utf-8"))
            for row in worksheet.iter_rows(values_only=True):
                values = [_stable_cell_value(value) for value in row]
                digest.update(json.dumps(
                    values,
                    sort_keys=True,
                    separators=(",", ":"),
                    ensure_ascii=False,).encode("utf-8"))
    finally:
        workbook.close()
    return digest.hexdigest()


def _hash_file(path):
    """Return a stable semantic fingerprint for one input file."""

    file_path = Path(path)
    if not file_path.is_file():
        return None
    if file_path.suffix.lower() in {".xlsx", ".xlsm"}:
        fingerprint = _hash_excel_file(file_path)
        method = "excel_cells"
    else:
        digest = hashlib.sha256()
        with file_path.open("rb") as stream:
            for chunk in iter(lambda: stream.read(1024 * 1024), b""):
                digest.update(chunk)
        fingerprint = digest.hexdigest()
        method = "bytes"
    return {
        "name": file_path.name,
        "method": method,
        "sha256": fingerprint,}


def _code_fingerprint(root_dir):
    """Return a fingerprint of the executable LEAF Python sources."""

    root = Path(root_dir)
    files = [root / "Runner.py"]
    files.extend(sorted((root / "src").rglob("*.py")))
    digest = hashlib.sha256()
    for path in files:
        if not path.is_file():
            continue
        digest.update(path.relative_to(root).as_posix().encode("utf-8"))
        digest.update(path.read_bytes())
    return digest.hexdigest()


def _run_input_files(user, forecast_path):
    """Return independent source files that determine one simulation run.

    Forecast, pattern, residual, and covariance workbooks are generated by
    LEAF from these source inputs, the normalized configuration, and the code
    fingerprint. Re-hashing their cells would duplicate that information and
    can take longer than an actual simulation.
    """

    del forecast_path
    root = Path(__file__).resolve().parents[2]
    candidates = []
    input_keys = ("historical_data_file", "external_hourly_profile_file",
                  "database_path")
    for key in input_keys:
        value = user.get(key)
        if not value:
            continue
        path = Path(str(value))
        candidates.append(path if path.is_absolute() else root / path)

    unique = {}
    for path in candidates:
        resolved = Path(path).resolve()
        unique[str(resolved)] = resolved
    return unique.values()


def build_run_id(user, forecast_path=None):
    """Build a content-based identifier for one complete simulation run."""

    non_semantic_keys = {
        "_config_path",
        "output",
        "keep_analysis_temp",
        "save_perturbed_forecasts",
        "save_plots",
        "save_projection_plots",
        "temporary_output_format",
        "simulations",
        "workers",
        "resume",}

    def normalize(value):
        """Normalize result-affecting values for stable serialization."""

        if isinstance(value, dict):
            return {
                str(key): normalize(item)
                for key, item in sorted(value.items(), key=lambda x: str(x[0]))
                if key not in non_semantic_keys}
        if isinstance(value, (list, tuple)):
            return [normalize(item) for item in value]
        if isinstance(value, Path):
            return str(value)
        return value

    semantic_user = normalize(user)
    fingerprints = []
    for path in _run_input_files(user, forecast_path):
        fingerprint = _hash_file(path)
        if fingerprint is not None:
            fingerprints.append(fingerprint)
    fingerprints.sort(key=lambda item: item["name"])

    root = Path(__file__).resolve().parents[2]
    payload = {
        "configuration": semantic_user,
        "files": fingerprints,
        "code": _code_fingerprint(root),}
    raw = json.dumps(
        payload, sort_keys=True, separators=(",", ":"),
        default=str).encode("utf-8")
    return hashlib.sha256(raw).hexdigest()[:16]



def _process_exists(pid):
    """Return whether a process exists without signalling it on Windows."""

    try:
        process_id = int(pid)
    except (TypeError, ValueError):
        return False
    if process_id <= 0:
        return False

    if os.name == "nt":
        import ctypes

        query_limited_information = 0x1000
        kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)
        handle = kernel32.OpenProcess(
            query_limited_information, False, process_id)
        if handle:
            kernel32.CloseHandle(handle)
            return True
        return ctypes.get_last_error() == 5

    try:
        os.kill(process_id, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    except OSError:
        return False
    return True



class ScenarioRunLock:
    """Prevent concurrent runs from writing to one scenario directory."""

    def __init__(self, output_dir):
        """Create a lock file path for the scenario output folder."""

        self.path = Path(output_dir) / ".leaf_run.lock"
        self.fd = None

    def __enter__(self):
        """Acquire the filesystem lock or reject a live owner."""

        self.path.parent.mkdir(parents=True, exist_ok=True)
        try:
            self.fd = os.open(
                self.path, os.O_CREAT | os.O_EXCL | os.O_WRONLY)
        except FileExistsError as exc:
            details = self.path.read_text(errors="ignore")
            pid = None
            for line in details.splitlines():
                if line.startswith("pid="):
                    try:
                        pid = int(line.split("=", 1)[1])
                    except ValueError:
                        pid = None
            stale = pid is None or not _process_exists(pid)
            if stale:
                self.path.unlink(missing_ok=True)
                return self.__enter__()
            raise RuntimeError(
                "Another LEAF run is already using this scenario output "
                f"folder. Lock details: {details}") from exc
        text = f"pid={os.getpid()}\nstarted={time.time()}\n"
        os.write(self.fd, text.encode("utf-8"))
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        """Release the filesystem lock."""

        if self.fd is not None:
            os.close(self.fd)
        try:
            self.path.unlink()
        except FileNotFoundError:
            pass

def should_save_perturbed_forecast(simulation_id, user):
    """Return whether one perturbed forecast should be written to disk."""

    if simulation_id <= 0:
        return False
    monte_carlo = user.get("monte_carlo", {}) or {}
    setting = monte_carlo.get("save_perturbed_forecasts", {})
    if not isinstance(setting, dict):
        return False
    if simulation_id == 1:
        return bool(setting.get("first_monte_carlo", True))
    return bool(setting.get("all_monte_carlo", False))


def save_perturbed_forecast(forecast_df, simulation_id,
                            forecast_dir, user):
    """Save one selected perturbed forecast without internal columns."""

    if not should_save_perturbed_forecast(simulation_id, user):
        return None

    forecast_dir.mkdir(parents=True, exist_ok=True)
    path = forecast_dir / f"Forecast_perturbed_{simulation_id}.xlsx"
    output = forecast_df.loc[:, [
        column for column in forecast_df.columns
        if not str(column).startswith("__LEAF_")
    ]]
    output.to_excel(path, index=False)

    if (
        simulation_id == 1
        and user.get("save_projection_plots", False)
    ):
        plot_path = (
            forecast_dir.parent / "Output" / "Plots"
            / "Forecast_perturbed_1.png")
        from src.forecasting.output_plots import save_energy_series_plot

        save_energy_series_plot(
            output,
            plot_path,
            user.get("energy_unit", "MWh"),
            "Date",)

    return path


def _detailed_output_format(user):
    """Return the canonical format for detailed time histories."""

    del user
    return "parquet"


def _output_frame(frame):
    """Return a write-only view without internal runtime metadata."""

    output = frame.copy(deep=False)
    output.attrs = {}
    return output


def _write_detailed_output(frame, base_path, user):
    """Write one large detailed table using the selected fast format."""

    output_format = _detailed_output_format(user)
    base_path = Path(base_path)
    base_path.parent.mkdir(parents=True, exist_ok=True)
    output = _output_frame(frame)
    if output_format == "xlsx":
        path = base_path.with_suffix(".xlsx")
        output.to_excel(path, index=False, engine="openpyxl")
        return path
    if output_format == "parquet":
        path = base_path.with_suffix(".parquet")
        try:
            output.to_parquet(path, index=False, compression="zstd")
            return path
        except ImportError:
            path = base_path.with_suffix(".csv.gz")
            output.to_csv(path, index=False, compression="gzip")
            return path
    path = base_path.with_suffix(".csv")
    output.to_csv(path, index=False)
    return path


def save_system_operation_output(result_df, simulation_id, output_dir, user):
    """Persist the complete system-operation history at detailed level."""

    if not should_save_detailed_output(user, simulation_id):
        return None
    output = result_df.copy()
    output["Date"] = pd.to_datetime(output["Date"])
    output_dir.mkdir(parents=True, exist_ok=True)
    base = (output_dir / "Detailed"
            / f"System_Operation_{simulation_id:06d}")
    return _write_detailed_output(output, base, user)


def save_hourly_generation_output(hourly_df, simulation_id,
                                  output_dir, user):
    """Save generation time histories only at detailed output level."""

    hourly_input = user.get("hourly_simulation", {})
    if not hourly_input.get("enabled", False):
        return None
    if not should_save_detailed_output(user, simulation_id):
        return None

    source_names = list(user.get("sources", {}))
    columns = ["Date", "Demand", "Total"]
    columns.extend(name for name in source_names if name in hourly_df.columns)
    output = hourly_df[columns].copy()
    output["Date"] = pd.to_datetime(output["Date"])
    output_dir.mkdir(parents=True, exist_ok=True)
    base = (output_dir / "Detailed"
            / f"Generation_{simulation_id:06d}")
    return _write_detailed_output(output, base, user)
